### ISSUE TITLE
 Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by NarasimmanSaravana1994** [otenim/Xception#2]
While training i'm facing below mentioned error,

WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/10
2019-12-05 12:44:29.722794: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-12-05 12:44:29.865201: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-12-05 12:44:30.425694: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-12-05 12:44:30.428112: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "fine_tune.py", line 248, in <module>
    main(args)
  File "fine_tune.py", line 160, in main
    period=args.snapshot_period_pre,
  File "/usr/local/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/usr/local/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/usr/local/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node block1_conv1/convolution}}]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node block1_conv1/convolution}}]]
	 [[loss/mul/_1797]]
0 successful operations.
0 derived errors ignored.

**Comment by NarasimmanSaravana1994** [comment]
@otenim I'm facing this issue

**Comment by otenim** [comment]
@NarasimmanSaravana1994 
Could you tell me the versions of CUDA and cudnn you use ?

**Comment by NarasimmanSaravana1994** [comment]
@otenim CUDA version - 10.0 

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

Tensor-flow --> 14 & 2.0 (gpu)

**Comment by otenim** [comment]
@NarasimmanSaravana1994 

Thanks. I guess CUDA and the cudnn libraries are correctly installed in your machine.
Then, I wanna make sure that what operating system you use. Could you tell me about it ?

Edit:
Could you show me the output when applying  `TF_FORCE_GPU_ALLOW_GROWTH=true` ?
I think this trick may work for your problem (try `TF_FORCE_GPU_ALLOW_GROWTH=true python fine_tune.py ...`).

**Comment by NarasimmanSaravana1994** [comment]
@otenim  Ubuntu 16.4 & cuddn libraries is installed proprly only because my another projects are using cuddn only it's working proprly..

**TF_FORCE_GPU_ALLOW_GROWTH=true**  -> which line i should paste ?

**Comment by NarasimmanSaravana1994** [comment]
`
[fine_tune.txt](https://github.com/otenim/Xception-with-Your-Own-Dataset/files/3927127/fine_tune.txt)

@otenim  This is my file ...
`

**Comment by otenim** [comment]
@NarasimmanSaravana1994 

Sorry for my confusing instruction.
You don't have to past the line in your code.
`TF_FORCE_GPU_ALLOW_GROWTH` is an environment variable the tf team officialy provides.
Please try executing `$ TF_FORCE_GPU_ALLOW_GROWTH=true python fine_tune.py ...` with your command line prompt.

**Comment by NarasimmanSaravana1994** [comment]
@otenim  Using the command i'm getting below error (core dump).




Using TensorFlow backend.
Dataset Preparing ................
Processing |################################| 2307/100
Dataset Preparing completed................
Training on 1845 images and labels
Validation on 462 images and labels
2019-12-05 19:46:32.482460: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2019-12-05 19:46:32.510768: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-12-05 19:46:32.511415: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Graphics Device major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:03:00.0
2019-12-05 19:46:32.511536: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-12-05 19:46:32.512280: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-12-05 19:46:32.512914: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-12-05 19:46:32.513061: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-12-05 19:46:32.513922: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-12-05 19:46:32.514563: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-12-05 19:46:32.516630: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-12-05 19:46:32.516700: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-12-05 19:46:32.517307: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-12-05 19:46:32.517866: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-12-05 19:46:32.518052: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-12-05 19:46:32.539253: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
2019-12-05 19:46:32.540218: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x48724a0 executing computations on platform Host. Devices:
2019-12-05 19:46:32.540231: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2019-12-05 19:46:32.628211: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-12-05 19:46:32.628744: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4895e50 executing computations on platform CUDA. Devices:
2019-12-05 19:46:32.628757: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Graphics Device, Compute Capability 7.5
2019-12-05 19:46:32.628870: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-12-05 19:46:32.629326: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Graphics Device major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:03:00.0
2019-12-05 19:46:32.629348: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-12-05 19:46:32.629356: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-12-05 19:46:32.629363: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-12-05 19:46:32.629370: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-12-05 19:46:32.629378: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-12-05 19:46:32.629385: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-12-05 19:46:32.629393: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-12-05 19:46:32.629417: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-12-05 19:46:32.629874: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-12-05 19:46:32.630316: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-12-05 19:46:32.630337: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-12-05 19:46:32.631036: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-12-05 19:46:32.631044: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-12-05 19:46:32.631048: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-12-05 19:46:32.631166: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-12-05 19:46:32.631632: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-12-05 19:46:32.632083: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2019-12-05 19:46:32.632100: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6846 MB memory) -> physical GPU (device: 0, name: Graphics Device, pci bus id: 0000:03:00.0, compute capability: 7.5)
Epoch 1/10
2019-12-05 19:46:36.817866: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-12-05 19:46:36.979905: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-12-05 19:46:37.902851: F tensorflow/stream_executor/cuda/ptxas_utils.cc:181] Non-OK-status: tensorflow::Env::Default()->DeleteFile(ptx_path) status: Not found: /tmp/tempfile-administrator-System-Product-Name-937fe700-26686-598f593d0e1e1; No such file or directory
Aborted (core dumped)

**Comment by NarasimmanSaravana1994** [comment]
@otenim  Used command 


TF_FORCE_GPU_ALLOW_GROWTH=true python fine_tune.py test_images/ classes.txt ./result

**Comment by NarasimmanSaravana1994** [comment]
@otenim  Is there any problem for Ubuntu OS?

**Comment by otenim** [comment]
@NarasimmanSaravana1994 

Thanks for your reporting.
I think your OS (Ubuntu 16.04) does not matter becaus it is officially supported.
Also, you have a enough gpu of much memory, so this is not a classical out of memory error.
OK, I'll check if my codebase works fine with my Ubuntu 16.04 machine, please wait little bit until it finishes.

**Comment by NarasimmanSaravana1994** [comment]
@otenim  Thanks for the response I'm waiting for your reply.

**Comment by NarasimmanSaravana1994** [comment]
@otenim  One suggestion from my side, 

There is no checkpoint option for any failure in between training. If any case I need to stop my training means I need to stop my training again I want to continue means to start my training my model stoped that step itself to continue.

**Comment by otenim** [comment]
@NarasimmanSaravana1994 
OK. I’ll deal with your suggestion.
Please wait little bit more.

**Comment by otenim** [comment]
@NarasimmanSaravana
Unfortunately, I could not reproduce your error with my Ubuntu 16.04, which means all the tests were passed without any exceptions.  If you use libraries of different versions from ones I listed in the repository, your problem may be solved by using the same versions of the libraries.
